package interfaces;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;







/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kthryn
 */
public class registro extends javax.swing.JFrame {
 conexion co= new conexion();
    Connection conet;
    Statement st;
    ResultSet rs;
    
    public registro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); 
    }
    
    //metodo para limpiar los campos de texto despues del registro
    public void limpiar(){
    txtidentificacion.setText("");
    txtnombre.setText("");
    txtceco.setText("");
    txtarea.setText("");
    txtcontratista.setText("");
}
   
    
    
    
    
    
    //metodo para guardar en la BD
  public void agregar() {
      
      
      //Validación
   String id = txtidentificacion.getText().trim();
String nombre = txtnombre.getText().trim();
String ceco = txtceco.getText().trim();
String area = txtarea.getText().trim();
String contratista = txtcontratista.getText().trim();

// Verifica si está vacío o aún tiene el texto del placeholder
if (id.isEmpty() || id.equalsIgnoreCase("número de identificación") ||
    nombre.isEmpty() || nombre.equalsIgnoreCase("Nombre completo") ||
    ceco.isEmpty() || ceco.equalsIgnoreCase("Ceco") ||
    area.isEmpty() || area.equalsIgnoreCase("Area") ||
    contratista.isEmpty() || contratista.equalsIgnoreCase("Contratista")) {

    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de registrar.");
    return;
}
    

    // Validar que el ID sea un número
    if (!id.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El número de identificación debe contener solo números.");
        return;
    }
        
        
        try{
           int idUsuario= Integer.parseInt(txtidentificacion.getText());
           String NombreCompleto=txtnombre.getText();
           String Ceco = txtceco.getText();
           String Area=txtarea.getText();
           String Contratista=txtcontratista.getText();
          

// segundo- enviar informacion obtenida a la BD

String sql= "insert into usuario(idUsuario,NombreCompleto,Ceco,Area,Contratista) values (?,?,?,?,?)";

conet= co.getConnection();
       PreparedStatement ps= conet.prepareStatement(sql);
ps.setInt(1,idUsuario);
ps.setString(2,NombreCompleto);
ps.setString(3,Ceco);
ps.setString(4,Area);
ps.setString(5,Contratista);
ps.executeUpdate();

//guardamos los datos de manera ordenada

        JOptionPane.showMessageDialog(null,"se ha realizado el registro");
}catch (SQLException e){
JOptionPane.showMessageDialog(null, "Error al registrar en la base de datos.");

        }
    }
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtidentificacion = new javax.swing.JTextField();
        txtceco = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        txtcontratista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        btnadmon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuinicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil-del-usuario (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        txtnombre.setForeground(new java.awt.Color(204, 204, 204));
        txtnombre.setText("Nombre completo");
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombreFocusLost(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtidentificacion.setForeground(new java.awt.Color(204, 204, 204));
        txtidentificacion.setText("número de identificación");
        txtidentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidentificacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidentificacionFocusLost(evt);
            }
        });

        txtceco.setForeground(new java.awt.Color(204, 204, 204));
        txtceco.setText("Ceco");
        txtceco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcecoFocusLost(evt);
            }
        });

        txtarea.setForeground(new java.awt.Color(204, 204, 204));
        txtarea.setText("Area");
        txtarea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtareaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtareaFocusLost(evt);
            }
        });

        txtcontratista.setForeground(new java.awt.Color(204, 204, 204));
        txtcontratista.setText("Contratista");
        txtcontratista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontratistaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontratistaFocusLost(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HIGABRA2.png"))); // NOI18N

        Registrarse.setBackground(new java.awt.Color(153, 211, 38));
        Registrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrarse.setText("REGISTRAR");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });

        btnadmon.setBackground(new java.awt.Color(153, 211, 38));
        btnadmon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadmon.setText("ADMINISTRAR");
        btnadmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidentificacion)
                    .addComponent(txtceco)
                    .addComponent(txtarea)
                    .addComponent(txtcontratista)
                    .addComponent(txtnombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnadmon)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtceco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontratista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadmon)
                    .addComponent(Registrarse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmenuinicio.setText("Inicio");
        jmenuinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuinicioActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmenuinicio.add(jMenuItem1);

        jMenuBar1.add(jmenuinicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
agregar();    
limpiar();
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void txtnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusGained
       if (txtnombre.getText().equals("Nombre completo")) {
    txtnombre.setText("");
    txtnombre.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_txtnombreFocusGained

    private void txtnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusLost
if (txtnombre.getText().isEmpty()) {
    txtnombre.setText("Nombre completo");
    txtnombre.setForeground(Color.GRAY);
}       
    }//GEN-LAST:event_txtnombreFocusLost
          
    private void txtidentificacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidentificacionFocusGained
          if (txtidentificacion.getText().equals("número de identificación")) {
    txtidentificacion.setText("");
    txtidentificacion.setForeground(Color.BLACK);
     } 
    }//GEN-LAST:event_txtidentificacionFocusGained

    private void txtidentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidentificacionFocusLost
        if (txtidentificacion.getText().isEmpty()) {
    txtidentificacion.setText("número de identificación");
    txtidentificacion.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_txtidentificacionFocusLost

    private void txtcecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcecoFocusGained
        if (txtceco.getText().equals("Ceco")) {
    txtceco.setText("");
    txtceco.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_txtcecoFocusGained

    private void txtcecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcecoFocusLost
         if (txtceco.getText().isEmpty()) {
    txtceco.setText("Ceco");
    txtceco.setForeground(Color.GRAY);
         }
    }//GEN-LAST:event_txtcecoFocusLost

    private void txtareaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtareaFocusGained
        if (txtarea.getText().equals("Area")) {
    txtarea.setText("");
    txtarea.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_txtareaFocusGained

    private void txtareaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtareaFocusLost
        if (txtarea.getText().isEmpty()) {
    txtarea.setText("Area");
    txtarea.setForeground(Color.GRAY);
         }
    }//GEN-LAST:event_txtareaFocusLost

    private void txtcontratistaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontratistaFocusGained
         if (txtcontratista.getText().equals("Contratista")) {
    txtcontratista.setText("");
    txtcontratista.setForeground(Color.BLACK); 
        }   
    }//GEN-LAST:event_txtcontratistaFocusGained

    private void txtcontratistaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontratistaFocusLost
         if (txtcontratista.getText().isEmpty()) {
    txtcontratista.setText("Contratista");
    txtcontratista.setForeground(Color.GRAY);
         }
    }//GEN-LAST:event_txtcontratistaFocusLost

    private void btnadmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmonActionPerformed
      admonusuarios admon= new admonusuarios();
      admon.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnadmonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        inicio in= new inicio();
    in.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmenuinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuinicioActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton btnadmon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmenuinicio;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtceco;
    private javax.swing.JTextField txtcontratista;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
